import type { Config } from "tailwindcss";

const config: Config = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "outline-variant": "#bcc9c6",
                "inverse-primary": "#6bd8cb",
                "on-surface-variant": "#3d4947",
                "error-container": "#ffdad6",
                "secondary-container": "#39b8fd",
                "error": "#ba1a1a",
                "on-background": "#0b1c30",
                "on-secondary": "#ffffff",
                "primary-fixed-dim": "#6bd8cb",
                "surface": "#f8f9ff",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#eff4ff",
                "surface-bright": "#f8f9ff",
                "tertiary-fixed-dim": "#ffb59a",
                "on-tertiary-container": "#fffbff",
                "surface-container-lowest": "#ffffff",
                "on-secondary-container": "#004666",
                "primary-container": "#008378",
                "surface-container": "#e5eeff",
                "on-primary-container": "#f4fffc",
                "on-tertiary-fixed-variant": "#773215",
                "tertiary-fixed": "#ffdbce",
                "surface-tint": "#006a61",
                "primary": "#00685f",
                "on-primary": "#ffffff",
                "surface-dim": "#cbdbf5",
                "secondary": "#006591",
                "background": "#f8f9ff",
                "surface-container-high": "#dce9ff",
                "on-secondary-fixed": "#001e2f",
                "inverse-on-surface": "#eaf1ff",
                "surface-container-highest": "#d3e4fe",
                "on-secondary-fixed-variant": "#004c6e",
                "surface-variant": "#d3e4fe",
                "outline": "#6d7a77",
                "secondary-fixed-dim": "#89ceff",
                "secondary-fixed": "#c9e6ff",
                "on-surface": "#0b1c30",
                "tertiary-container": "#b05e3d",
                "on-tertiary-fixed": "#370e00",
                "on-primary-fixed": "#00201d",
                "tertiary": "#924628",
                "primary-fixed": "#89f5e7",
                "inverse-surface": "#213145",
                "on-primary-fixed-variant": "#005049",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                "container-padding": "2rem",
                "card-gap": "1rem",
                base: "4px",
                gutter: "1.5rem",
                "section-margin": "2.5rem",
            },
            fontFamily: {
                "body-lg": ["Geist", "sans-serif"],
                "headline-md": ["Geist", "sans-serif"],
                "headline-lg": ["Geist", "sans-serif"],
                "label-sm": ["Geist", "sans-serif"],
                "label-md": ["Geist", "sans-serif"],
                display: ["Geist", "sans-serif"],
                "body-md": ["Geist", "sans-serif"],
            },
            fontSize: {
                "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
                "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
                "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
                display: ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
};
export default config;